version: "2"
services:
  frontend:
    build: frontend
    restart: always
    ports:
      - "0.0.0.0:7770:5000"
  backend:
    build: backend
    restart: always
    ports:
      - "0.0.0.0:7771:8080"
    environment:
      - DATABASE_URL=jdbc:mysql://mysql:3306/ticket_system
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=ticket_system
    volumes:
      - /srv/data/ticket_system/mysql:/var/lib/mysql
